[font]
size = 15.0
normal = { family = "Iosevka", style = "Light Extended" }
bold = { family = "Iosevka", style = "Light Extended Bold" }
italic = { family = "Iosevka", style = "Light Extended Italic" }
bold_italic = { family = "Iosevka", style = "Light Extended Bold Italic" }

[colors.primary]
background = "0x020202"
