[font]
size = 14.0
normal = { family = "Iosevka Fixed", style = "Extended" }
bold = { family = "Iosevka Fixed", style = "Extended Bold" }
italic = { family = "Iosevka Fixed", style = "Extended Italic" }
bold_italic = { family = "Iosevka Fixed", style = "Extended Bold Italic" }
