[font]
size = 14.0
normal = { family = "Iosevka Extended", style = "Regular" }
bold = { family = "Iosevka Extended", style = "Bold" }
italic = { family = "Iosevka Extended", style = "Italic" }
bold_italic = { family = "Iosevka Extended", style = "Bold Italic" }
